openapi: 3.0.3
info:
  title: Truck
  version: 1.0.0
servers:
  - url: "http://localhost"
    description: "Localhost"
paths: {}

components:
  parameters:
    TruckOrderBy:
      in: query
      name: "order_by"
      required: false
      schema:
        $ref: "#/components/schemas/TruckOrderBy"
  responses:
    PaginatedTrucks:
      description: "Successful operation"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PaginatedTrucks"
    TruckResponse:
      description: "Successful operation"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Truck"
  schemas:
    TruckOrderBy:
      type: string
      enum:
        - trucks.id
        - trucks.name
      default: trucks.id
    Truck:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
      required:
        - id
        - name
        - created_at
        - updated_at
    PaginatedTrucks:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/Truck"
        current_page:
          type: integer
        from:
          type: integer
        to:
          type: integer
        total:
          type: integer
      required:
        - data
        - current_page
        - from
        - to
        - total
